### ISSUE TITLE
Error reading version in ACA Log

### ISSUE THREAD

**Issue by apldev3** [nsacyber/HIRS#3]
Multiple occurances of a Version Error appear in the AttestationCA.log file:

```
2018-09-04 14:28:36 [hirs.utils.VersionHelper.getVersion] WARN  : Error reading version
java.lang.IllegalArgumentException: resource VERSION not found.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-18.0.jar:?]
        at com.google.common.io.Resources.getResource(Resources.java:197) ~[guava-18.0.jar:?]
        at hirs.utils.VersionHelper.getFileContents(VersionHelper.java:53) ~[HIRS_Utils-1.0.1-SNAPSHOT.jar:?]
        at hirs.utils.VersionHelper.getVersion(VersionHelper.java:42) [HIRS_Utils-1.0.1-SNAPSHOT.jar:?]
        at hirs.utils.VersionHelper.getVersion(VersionHelper.java:29) [HIRS_Utils-1.0.1-SNAPSHOT.jar:?]
        at hirs.data.persist.DeviceInfoReport.<init>(DeviceInfoReport.java:145) [HIRS_Utils-1.0.1-SNAPSHOT.jar:?]
        at hirs.attestationca.AbstractAttestationCertificateAuthority.parseDeviceInfo(AbstractAttestationCertificateAuthority.java:593) [AbstractAttestationCertificateAuthority.class:?]
        at hirs.attestationca.AbstractAttestationCertificateAuthority.processDeviceInfo(AbstractAttestationCertificateAuthority.java:654) [AbstractAttestationCertificateAuthority.class:?]
        at hirs.attestationca.AbstractAttestationCertificateAuthority.doSupplyChainValidation(AbstractAttestationCertificateAuthority.java:432) [AbstractAttestationCertificateAuthority.class:?]
        at hirs.attestationca.AbstractAttestationCertificateAuthority.processIdentityClaimTpm2(AbstractAttestationCertificateAuthority.java:387) [AbstractAttestationCertificateAuthority.class:?]
        at hirs.attestationca.rest.RestfulAttestationCertificateAuthority.processIdentityClaimTpm2(RestfulAttestationCertificateAuthority.java:93) [RestfulAttestationCertificateAuthority.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
```

**Comment by apldev3** [comment]
Upon investigation the issue seems to be occurring because of the VERSION file not getting packaged into the HIRS_AttestationCA RPM correctly.

**Comment by apldev3** [comment]
Apparently it's not as simple as it was made out to be above. In reality, what we want is to have is to have the TPM 2.0 provisioner send over its version as a Client Version of sorts as opposed to having the AttestationCA (i.e. the server) throw in its own version.

**Comment by apldev3** [comment]
The latest merge request ensures that both the ACA and TPM 2 Provisioner have their own versions and that the TPM2 Provisioner submits its version to the ACA appropriately.
