### ISSUE TITLE
RIM Tool build on Windows query

### ISSUE THREAD

**Issue by Cyborg1138** [nsacyber/HIRS#477]
https://github.com/nsacyber/HIRS/blob/master/HIRS_AttestationCAPortal/src/main/webapp/docs/TCG%20Rim%20Tool%20User%20Guide%202.1.pdf

Appendix B states that building the RIM Tool on Windows  is not supported. Yet the RIM Tool has a gradlew.bat file that runs, but fails its unit tests as detailed below.

There are typos in the description at: https://github.com/nsacyber/HIRS/tree/master/tools/tcg_rim_tool e.g. distrobustions and a more detailed description plus a link to the user guide would be helpful, although this link exists elsewhere.

Note that I have successfully built the RIM Tool in Visual Studio Code without gradle/Maven mainly to gain insight into what it is doing using the debugger, and it runs and produces results without apparent issues.

The point is that it seems strange to supply the gradlew.bat file when the documentation states it isn't supported. We are attempting to use this tool on Windows as part of our tool chain and would appreciate feedback as to why is isn't supported. The swidtag files it produces on Windows appear to load into a Centos 7 based HIRS ACA server when this operation is performed manually via the GUI (but NOT when posted via the provisioner as part of an identity claim that includes a human readable Support RIM) and their contents/fields can be viewed successfully.

I have not investigated the reason for the unit test failures. If this is easy to resolve, why not resolve it and state the RIM tool is supported on Windows?

 gradlew.bat clean build

> Task :tools/tcg_rim_tool:test

Gradle suite > Gradle test > hirs.swid.TestSwidTagGateway.testCreateBaseWithCert FAILED
    java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:494)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at org.testng.Assert.assertTrue(Assert.java:52)
        at hirs.swid.TestSwidTagGateway.testCreateBaseWithCert(TestSwidTagGateway.java:54)

Gradle suite > Gradle test > hirs.swid.TestSwidTagGateway.testCreateBaseWithoutCert FAILED
    java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:494)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at org.testng.Assert.assertTrue(Assert.java:52)
        at hirs.swid.TestSwidTagGateway.testCreateBaseWithoutCert(TestSwidTagGateway.java:67)

Gradle suite > Gradle test > hirs.swid.TestSwidTagGateway.testValidateSwidTag FAILED
    java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/PitcherJ/Documents/HIRS/HIRS-master/tools/tcg_rim_tool/build/resources/test/TpmLog.bin
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at hirs.swid.utils.HashSwid.getHashValue(HashSwid.java:67)
        at hirs.swid.utils.HashSwid.get256Hash(HashSwid.java:30)
        at hirs.swid.SwidTagValidator.validateFile(SwidTagValidator.java:135)
        at hirs.swid.SwidTagValidator.validateSwidTag(SwidTagValidator.java:119)
        at hirs.swid.TestSwidTagGateway.testValidateSwidTag(TestSwidTagGateway.java:78)
0/3 tests passed

3 tests completed, 3 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tools/tcg_rim_tool:test'.
> There were failing tests. See the report at: file:///C:/Users/PitcherJ/Documents/HIRS/HIRS-master/tools/tcg_rim_tool/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
7 actionable tasks: 7 executed

**Comment by iadgovuser26** [comment]
gradlew.bat is a script provided by gradle. While the tool will build windows is is not a feature we routinely test. The above tests will fail in many cases when any of the files have been modified without adjusting the tests. Try using the "-x test"  with gradle to skip the tests.

**Comment by iadgovuser26** [comment]
Closing due to inactivity, Please resubmit the issue if has not been addressed satisfactorily.
