### ISSUE TITLE
Rimtool validate function is broken

### ISSUE THREAD

**Issue by chubtub** [nsacyber/HIRS#646]
When attempting to validate a RIM with `rim -v` the rimtool throws the following error:

`Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.trustStore" is null
	at hirs.utils.rim.ReferenceManifestValidator.getCertFromTruststore(ReferenceManifestValidator.java:312)
	at hirs.utils.rim.ReferenceManifestValidator.validateSwidtagFile(ReferenceManifestValidator.java:248)
	at hirs.swid.Main.main(Main.java:42)`

**Comment by chubtub** [comment]
Closed by PR650.
