### ISSUE TITLE
Dockerize TPM 1.2 Provisioner

### ISSUE THREAD

**Issue by apldev3** [nsacyber/HIRS#71]
With the recent closure of #46 and the ongoing work in #67, an effort should be made to bring the old TPM 1.2 Provisioner in line with the ACA and TPM 2.0 Provisioner insofar as systems tests are concerned. The initial step is to make the TPM 1.2 Provisioner able to be run from within a Docker container. This ticket will track work towards that end.

**Comment by apldev3** [comment]
For this task it appears that we may only get so far as dockerizing the application, but testing it becomes another question. The main problem at this juncture is to setup the TPM Emulator in a way that the 1.2 Provisioner can speak to it from a Docker container. Currently, it may be possible to setup the TPM Emulator on the Travis-Ci VM, but doing it within the Docker container entirely has to be ruled out as Docker containers have no control over the host's Kernel Modules which is what the TPM 1.2 Emulator requires.

**Comment by busaboy1340** [comment]
Just a quick question (Lawrence wasn't too sure either), we've been using the TPM 1.2 Emulator from https://sourceforge.net/projects/ibmswtpm/. And it looks like your pulling the emulator from https://github.com/PeterHuewe/tpm-emulator. Was there a reason to use the latter?

**Comment by apldev3** [comment]
When I started up the Vagrant box that's running systems tests on the other pipeline it appeared to running the latter, thus for consistencies sake, I decided to go down that path.

**Comment by apldev3** [comment]
Yeah @busaboy1340 I'm shifting towards the ibmswtpm as it doesn't appear to require the same level of privileges as the PeterHuewe one. Seems like ibmswtpm will work better with Docker involved. That being said, I'm having issues even building the TPM. Do you all get compilation errors from the latest version of the Software TPM?

**Comment by apldev3** [comment]
Nevermind I got it.

**Comment by busaboy1340** [comment]
I've been playing around with the IBM one. Got it to build, but get the error below when provisioning in the docker container. We installed it on a different Centos7 machine and it works fine. Probably  missing something in my configuration. Maybe you'll have better luck.

Caused by: java.security.cert.CertificateException: No subject alternative names present
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:145)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:94)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:200)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)

**Comment by busaboy1340** [comment]
I've been playing around with the IBM one. Got it to build, but get the error below when provisioning in the docker container. We installed it on a different Centos7 machine and it works fine. Probably  missing something in my configuration. Maybe you'll have better luck.

Caused by: java.security.cert.CertificateException: No subject alternative names present
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:145)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:94)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:200)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)

**Comment by busaboy1340** [comment]
I was able to add the subjectAltName to the cert and update the /etc/hosts accordingly. But still no luck. To be continued...

**Comment by apldev3** [comment]
I have a feeling it might have to do with us using hardcoded IPs rather than using DNS to resolve it, which seems to be a little quirk of Java per this StackOverflow post: https://stackoverflow.com/questions/10258101/sslhandshakeexception-no-subject-alternative-names-present

**Comment by busaboy1340** [comment]
Yeah, I took out the static IPs also. Same error.
